# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x, lts/* ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: ğŸ£ Checkout repository
        uses: actions/checkout@v2
      - name: âš™ï¸ Installing node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: ğŸ” Getting yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: ğŸ’¾ Saving caches
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: ğŸ£ Install dependencies
        run: yarn install --frozen-lockfile
      - name: ğŸ› ï¸ Build module
        run: yarn build
      - name: ğŸ¯ Run tests
        run: yarn jest
